revamped Passwd() utility-function
sylabs/singularity pull request #1531
Opened 2023-04-06 22:03 UTC by preminger

## Description of the Pull Request (PR):

The way the Passwd() utility-function (internal/pkg/util/fs/files/passwd.go:22) worked until now, it was only able to append a new line to what it got as input (from the base layer).

This meant that, for example, to override the homedir of a regular user, we would simply add a modified line (with the custom homedir) to the in-container /etc/passwd; but to override the homedir of root (when running singularity itself as root, or when running with `--fakeroot`), we couldn't do that – since there was already a "root" line in the base layer's /etc/passwd – and we resorted to an entirely different method, namely, overriding the `$HOME` environment variable upon container initialization.

In addition to being non-uniform, the approach involving environment variables can also give rise to an internally inconsistent state, where, when we're root inside the container, our $HOME is set to one thing (a custom homedir) but the /etc/passwd file still has `/root` as the homedir for the root user.

A more uniform approach, which also avoids this inconsistent state described above, is possible: change the Passwd() utility-function so that when "adding" a line to /etc/passwd it first checks if a line with the corresponding uid already exists, and if it does, replaces that specific line instead of appending a new line to the file.

2023-04-06 22:08 UTC, preminger commented
PLEASE NOTE THE "PERFORMANCE CONSIDERATIONS" SECTION IN THE INITIAL COMMENT.

2023-04-10 10:32 UTC, dtrudg requested changes
A CHANGELOG.md entry detailing the behaviour change is required (w.r.t. what happens with /etc/passwd vs $HOME before and after this change).

General approach is fine, but the dependencies added here need to be reviewed / replaced.

https://github.com/stat0s2p/etcpwdparse is a fork of https://github.com/astromechza/etcpwdparse without any changes. In this type of situation, generally prefer the original. Also, that repo doesn't have a `go.mod`. If there's an alternative that is using modern go modules it'd be preferred.

github.com/revel/cmd probably isn't a good choice to import just to access a function to read all lines from a file. revel is a large web framework, and revel/cmd the CLI stuff for it, so it's not surprising it brings in quite a lot of other dependencies. These will (such is the nature of a web framework) introduce quite a lot of dependency churn vs the benefit.

Using bufio.Scanlines (i.e. this pattern https://www.golangprograms.com/golang-read-file-line-by-line-to-string.html) is more verbose, but will avoid bringing in 7 dependencies.

2023-04-10 16:07 UTC, preminger commented
Concerning the last part: if I understood your question correctly, you're talking about a situation where the base layer for the singularity container already brings in a `/etc/passwd` file containing a user `dave`, and you're also running singularity in user mode (i.e., not as root and not with `--fakeroot`) from a host user called `dave`.

Looking at the code *before* this change, it looks like what would have happened is that we would write an additional line for `dave` into the container's `/etc/passwd` anyway (internal/pkg/util/fs/files/passwd.go:40-44). And, based on how it behaved when there were two lines for the user `root`, I have to assume it would simply ignore the second `dave` line, and so this additional line would have no effect.

The new code, as it stands, would *replace* the existing `dave` line in the container's `/etc/passwd`, **but only if both `dave`s had the same user id**. In fact, it would replace the `dave` line in the container's `/etc/passwd` with a line for `omer` if we were running as `omer` in the host, and `omer`'s user id in the host was the same as `dave`'s user id in the container's base layer.

I can see how this might introduce fairly significant backward-compatibility issues, depending on which use cases are out there.

Please advise.

2023-04-24 13:55 UTC, preminger commented
Oh, sorry @dtrudg – I think I saw a previous version of your last comment that said something like "let's mirror the behavior that Docker has" and I was contemplating the best chance to find out what that was (spelunking in the docs, or just poking around with docker myself), but I see now that you've edited the comment. I think I'm good to go from here. Thanks!

2023-04-25 09:05 UTC, dtrudg reviewed
Looks sensible to me. Please could you rebase against main, and I'll take a final look before I put a :heavy_check_mark:  on it.

2023-04-25 13:18 UTC, closed without merging