oci: support --workdir
sylabs/singularity pull request #1689
Opened 2023-05-17 20:07 UTC by preminger

## Description of the Pull Request (PR):

Provides support for `--workdir` in OCI-mode.

Specifying `--workdir <dir>` means that <dir>/tmp and <dir>/var_tmp on the host will be mapped, respectively, to /tmp and /var/tmp in the container.

Also changed the usage string for the `--workdir` option to make it clear that $HOME is unaffected by this option. (The latter can be manipulated separately, using the `--home` option.) This is so both in native mode and OCI mode.

### This fixes or addresses the following GitHub issues:

 - Fixes #1483

2023-05-17 20:21 UTC, preminger commented on e2e/actions/oci.go
> +			// This part needs to be in privileged mode because of the following
@dtrudg: Please have a look at this comment. This is what was behind the somewhat opaque msgs I sent you on Slack earlier today.

If the behavior described in the comment is what we should be expecting, then it is indeed just a matter of making the e2e test resilient to it, and this should be good to go.

But if this behavior shouldn't be happening (i.e., if the intermediate dirs should be mkdir'd with non-shifted uid/gid, or not mkdir'd at all), then we need to discuss more.

Note also that this is consistent with the behavior of native mode, which also mkdirs missing intermediate directories as needed in this scenario, but there are uid/gid maps in play and they are simply created under the ownership of the user running singularity.

2023-05-17 20:24 UTC, preminger commented on e2e/actions/common.go
> +func workspaceDirsGenerator(t *testing.T, hostCanaryDir, hostHomeDir, hostWorkDir, hostCanaryFile string) {
The linter started complaining about how many lines of code e2e/actions/actions.go and e2e/actions/oci.go had in common (fair point, linter!), so I refactored this function out and put it in this new file.

It's not "maximalist" refactoring – perhaps more could be refactored out – but as things stand now, there _are_ differences between actions.go and oci.go in some of the other nearly-identical portions of the relevant code. (For example, the difference in `checkHostFn()`, discussed in a separate comment in oci.go).

2023-05-18 09:12 UTC, dtrudg requested changes
Looks pretty good to me. One issue that I have found...

`--workdir` accepts a relative `./workdir` path, but then it can't mount `--scratch` dirs:

```
10:08 am $ singularity run --oci --workdir ./workdir --scratch /scratch docker://alpine
2023/05/18 10:08:48  info unpack layer: sha256:8a49fdb3b6a5ff2bd8ec6a86c05b2922a0f7454579ecc07637e94dfd1d0639b6
2023-05-18T09:08:48.911142Z: error stat'ing file `workdir/scratch/scratch`: No such file or directory

10:08 am $ singularity run --oci --workdir $(pwd)/workdir --scratch /scratch docker://alpine
2023/05/18 10:08:57  info unpack layer: sha256:8a49fdb3b6a5ff2bd8ec6a86c05b2922a0f7454579ecc07637e94dfd1d0639b6
~ $ 
```

Native mode actually has a similar issue... so you could say this PR is accurately replicating native mode :-) However, I think the behaviour should probably be fixed here, and filed as a bug for native mode.

```
$ singularity run --contain --workdir ./workdir --scratch /scratch docker://alpine
INFO:    Using cached SIF image
FATAL:   container creation failed: could not bind scratch directory workdir/scratch/scratch into container: source must be an absolute path
```

2023-05-18 14:53 UTC, dtrudg approved these changes

2023-05-18 15:02 UTC, merged