WIP: more robust way of setting IFS to newline
sylabs/singularity pull request #1708
Opened 2023-05-26 22:11 UTC by preminger

## Description of the Pull Request (PR):

As part of the function of `singularity inspect`, an ad-hoc shell script is set up, by concatenating programmatically-generated snippets of shell code. One of these snippets, created in cmd/internal/cli/inspect.go:227, includes a line whose function is to set IFS (the Input Field Separator) _back_ to newline in the scope of the `cat_file()` function, despite being set to ":" (colon) in the global scope (cmd/internal/cli/inspect.go:256).

However, the way this was done until now uses escaping of the newline, as follows: `local IFS=$'\n'`
This escaping apparently doesn't work on certain platforms, resulting in the relevant input being split using the character "n" as the relevant delimiter, rather than using newlines.

I have verified that it fails on Debian 11 "bullseye" on amd64, and the user who reported #1704 encountered the same thing on Ubuntu 22.04 "jammy" on amd64. There is a newer syntax for this - `local IFS=$'...'` - but there is a worry this won't work on older systems; see discussion in [this](https://stackoverflow.com/questions/16831429/when-setting-ifs-to-split-on-newlines-why-is-it-necessary-to-include-a-backspac) StackOverflow post. In the same post, however, it is mentioned that there is a rather simple and possibly more robust way to achieve the same effect, namely, to use a literal newline between double-quotes:

```
      <clipped>
      local IFS="
"
      <clipped>
```

This PR replaces the previous implementation, using `$'\n'`, with the one above.

### This fixes or addresses the following GitHub issues:

 - Fixes #1704

2023-05-28 16:34 UTC, preminger commented
fyi - tried cherry-picking _only_ the e2e test commit (`445e9a6155b3ad8377d752280841bd537f5caa10`) onto a clone of `main` to make sure the e2e test indeed fails _without_ the fix itself (`6b02eb5a7347d7c3694806b15f591042027533f6`), and it indeed does, though only on `amd64`. This is consistent with what's reported in #1704 , and the e2e test is based directly on the `.def` file provided by @Flamefire there.

2023-05-29 21:21 UTC, tri-adam approved these changes
LGTM

2023-05-30 08:13 UTC, dtrudg requested changes
Good catch. Code / test LGTM.

Please could you just add a line to the CHANGELOG highlighting this bugfix. Thanks.

2023-05-30 14:29 UTC, dtrudg approved these changes

2023-05-30 14:39 UTC, merged