test: use `T.TempDir` to create temporary test directory
sylabs/singularity pull request #905
Opened 2022-07-14 13:34 UTC by Juneezee

## Description of the Pull Request (PR):

A testing cleanup. 

This pull request replaces `ioutil.TempDir` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 

This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.

Reference: https://pkg.go.dev/testing#T.TempDir

```go
func TestFoo(t *testing.T) {
	// before
	tmpDir, err := ioutil.TempDir("", "")
	if err != nil {
		t.Fatal(err)
	}
	defer os.RemoveAll(tmpDir)

	// now
	tmpDir := t.TempDir()
}
```

### This fixes or addresses the following GitHub issues:

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/main/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md)
- Added tests to validate this PR, linted with `make check`  and tested this PR locally with a `make test`, and `make testall` if possible (see CONTRIBUTING.md).
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/main/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/main/CONTRIBUTORS.md)

2022-07-14 13:48 UTC, dtrudg requested changes
Hi @Juneezee - thanks for the PR.

As implemented now, the changes lose some information that aids debugging. In various places we are using multiple tempDirs and applying a prefix to the tempDir... e.g. 

https://github.com/sylabs/singularity/pull/905/files#diff-87433ad07610d652c4b61f1f3f15660e55d8f5032a9010856ae1cda222d6e9e1

... will have two temp dirs, one prefixed "copywithtar-src" and one "copy-with-tar-dst"

This may seem minor, but it is extremely beneficial when working in this area of the code.

I think it'd be fine to use `t.TempDir()` for purely anonymous tempDirs, where we aren't enforcing our own prefix... but I'd rather keep the ones that use a prefix, for good reason, in place as they are.

Thanks!

2022-07-14 14:03 UTC, Juneezee commented
> Hi @Juneezee - thanks for the PR.
> 
> As implemented now, the changes lose some information that aids debugging. In various places we are using multiple tempDirs and applying a prefix to the tempDir... e.g.
> 
> https://github.com/sylabs/singularity/pull/905/files#diff-87433ad07610d652c4b61f1f3f15660e55d8f5032a9010856ae1cda222d6e9e1
> 
> ... will have two temp dirs, one prefixed "copywithtar-src" and one "copy-with-tar-dst"
> 
> This may seem minor, but it is extremely beneficial when working in this area of the code.
> 
> I think it'd be fine to use `t.TempDir()` for purely anonymous tempDirs, where we aren't enforcing our own prefix... but I'd rather keep the ones that use a prefix, for good reason, in place as they are.
> 
> Thanks!

@dtrudg Hi, thanks for reviewing this PR. `srcRoot` and `desRoot` are still easily distinguishable in debugging because `t.TempDir()` always return a unique directory. I have attached a sample code in Go playground below.

Go playground link: https://go.dev/play/p/Y7QZMR9lpjG

```go
package main

import (
	"fmt"
	"testing"
)

func TestCopyWithTar(t *testing.T) {
	srcRoot := t.TempDir()
	fmt.Printf("srcRoot: %v\n", srcRoot)

	dstRoot := t.TempDir()
	fmt.Printf("dstRoot: %v\n", dstRoot)
}
```

```
=== RUN   TestCopyWithTar
srcRoot: /tmp/TestCopyWithTar3440167842/001
dstRoot: /tmp/TestCopyWithTar3440167842/002
--- PASS: TestCopyWithTar (0.00s)
PASS
```

Let me know if you think it's better to keep `copywithtar-src-` and `copywithtar-des-` for now. I'lm happy to revert the changes :smile:

2022-07-14 21:37 UTC, dtrudg commented
> @dtrudg Hi, thanks for reviewing this PR. `srcRoot` and `desRoot` are still easily distinguishable in debugging because `t.TempDir()` always return a unique directory. I have attached a sample code in Go playground below.

> === RUN   TestCopyWithTar
> srcRoot: /tmp/TestCopyWithTar3440167842/001
> dstRoot: /tmp/TestCopyWithTar3440167842/002
> --- PASS: TestCopyWithTar (0.00s)
> PASS

Hi @Juneezee - if you add a `t.Logf` to show the locations as you did in your example code, I think that'll do. Appreciate that they are named uniqueley - but `001` and `002` aren't immediately obvious, so I think it'd be good to point it out in the test output. Thanks!

2022-07-15 16:39 UTC, dtrudg approved these changes
Thanks!

2022-07-15 16:44 UTC, dtrudg commented
CircleCI is currently failing to accept the webhook for the PR - will get it merged a bit later when that works. Thanks again.

2022-07-15 18:00 UTC, Juneezee commented
@dtrudg No worries! 😄

2022-07-20 14:32 UTC, dtrudg commented
@Juneezee - I can't get a satisfactory response from CircleCI about the issue here. The only thing they have for us to try isn't feasible as it would require completely removing and reauthorizing CircleCI for our GitHub organization. We can't do this due to the disruption it would cause.

To get this merged I'm going to open a PR and cherry-pick your commit into it, preserving you as the author. Hopefully that'll work and I'll get this merged asap. Thanks again!

2022-07-20 14:33 UTC, Juneezee commented
@dtrudg Would it work if I force push and try to trigger the CI? :thinking:

2022-07-20 14:39 UTC, dtrudg commented
@Juneezee - you can try to do another force push... but you would need to make a change, or rebase so it's not the same commit, I believe.

We seem to have the same issue as has been reported on CircleCI forums in the past by others, without any resolution noted.

The only information I've been given is that:

> Checking the logs, on our end, it shows the user who performed the PR, is not the one that is attached to the username

... but this doesn't make any sense to me... and your previous commits did trigger CI 🤷

2022-07-20 14:46 UTC, dtrudg commented
> EDIT: It works

Well - that's good... still a mystery why redelivering the web hook, or me trying to re-trigger it just failed 🤷 

I guess we may never know what's going on!

2022-07-20 14:46 UTC, merged